spring:
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/semillero
    username: semillero
    password: semillero
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

server.compression:
  enabled: true
  mime-types: application/json

logging.file: semillero.log

---
spring:
  profiles: production
  datasource:
    url: jdbc:mariadb://semillero-db/semillero
    username: root
    password:
